### ISSUE TITLE
Not compite with stronghold

### ISSUE THREAD

**Issue by octefg** [tbabic/battlebros-north-expansion#1]
Hi, on the description page it says it works with strong hold, but when I got in the game, it says not compatible with stronghold 2. Does this means I should download older versions?

and also, I tried this mod before it broke the save. Maybe is old version? I wonder does it fixed? This was the code before. I really love this mod, I hope this time is all fixed
![IMG_8213](https://github.com/tbabic/battlebros-north-expansion/assets/166318046/ab8ffd94-66cf-412a-bcd7-b769acecfa12)

**Comment by tbabic** [comment]
Try downloading the latest version, it should be okay then
