### ISSUE TITLE
File name doesn’t match code

### ISSUE THREAD

**Issue by octefg** [tbabic/battlebros-north-expansion#2]
scripts/entity/tactical/humans/barbarian_champion_guest.nut

The file name is barbarian_champion_guest.nut, but the first line of code is this.barbarian_champion. Is this is a mistake or did on purpose?

**Comment by tbabic** [comment]
It's most certainly an issue (due to copy-pasting), strange it didn't cause problems in my playthroughs.

It will be fixed in the next release.

**Comment by octefg** [comment]
Thank you for your reply, I noticed this for very long time, I been play this mod even before the release on Nexus from houshou. Very good work, keep it up :)
